version: "3"
services:
  yelpcamp:
    image: gabendocker/yelpcamp
    depends_on:
      - mongodb
    environment:
      - DB_CONNECTION=${DB_CONNECTION}
      - SESSION_PSW=${SESSION_PSW}
    ports:
      - 4000:4000

  mongodb:
    image: mongo:4.4.6
    ports:
      - 27017:27017
    volumes:
      - mongo-data:/data/db

volumes:
  mongo-data:
    driver: local
